# This is a basic workflow to help you get started with Actions

name: Pull Request

on:
  push:
    branches: [ "config_cicd" ]
# OK
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install gem
        run: bundler install
          
      - name: Upload to drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }} 
          filename: "text.docx"
          folderId: ${{ secrets.FOLDERID }}
          overwrite: "true"
