# This is a basic workflow to help you get started with Actions

name: Pull Request

on:
  push:
    branches: [ "config_cicd" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Fastlane Action

        uses: maierj/fastlane-action@v3.0.0
        with:
          # The lane that should be executed.
          lane: 'beta'
          subdirectory: 'ios'
